### ISSUE TITLE
 Unable to cast object of type 'Org.BouncyCastle.Asn1.DerSequence' to type 'Org.BouncyCastle.Asn1.DerInteger'.

### ISSUE THREAD

**Issue by MichaelBravermanClearPoint** [claboran/ForceDotNetJwtCompanion#14]
Hi, 
I am trying to use the code, but getting the error:
System.InvalidCastException : Unable to cast object of type 'Org.BouncyCastle.Asn1.DerSequence' to type 'Org.BouncyCastle.Asn1.DerInteger'.
Is that something expected?

**Comment by claboran** [comment]
@MichaelBravermanClearPoint - no that is nothing expected. What key format did you use?

**Comment by svraaij** [comment]
i can reproduce it, looking on it

**Comment by svraaij** [comment]
you can try this:
  public static PrivateKeyWrapper CreatePrivateKeyWrapper(string key)
    {
        var asymmetricKeyParameter = PrivateKeyFactory.CreateKey(Convert.FromBase64String(CommonHelpers.RemoveHeaderFooterFromKey(key)));
        var rsaKeyParameter = (RsaKeyParameters)asymmetricKeyParameter;
        
        return new PrivateKeyWrapper
        {
            Modulus = rsaKeyParameter.Modulus,
            Exponent = rsaKeyParameter.Exponent
        };
    }
