### ISSUE TITLE
Make branch 2023 ready (with small updates on nuget/vars/formats)

### ISSUE THREAD

**Issue by svraaij** [claboran/ForceDotNetJwtCompanion#16]
Make branch 2023 ready (with small updates on nuget/vars/formats)

**Comment by svraaij** [comment]
How can i make an merge request with my changes?

**Comment by claboran** [comment]
@svraaij - Nice :+1:   Will invite you as Collaborator. Ok for you?

**Comment by svraaij** [comment]
Ok!,. Will push my Merge request soon

**Comment by svraaij** [comment]
Pull request ready
