### ISSUE TITLE
Issue When using MyDomain

### ISSUE THREAD

**Issue by bwanshoom** [claboran/ForceDotNetJwtCompanion#5]
This doesn't work when an instance uses My Domain. The instance URL might be something like https://testy.my.salesforce.com, but the Audience of the JWT needs to be either https://login.salesforce.com (for PROD) or https://test.salesforce.com. 

Also, you might consider renaming AddTokenEndpoint since it's misleading - this isn't the endpoint that's being added, it's the audience.

**Comment by claboran** [comment]
@bwanshoom: Thanks for pointing this out, you are completely right. Will fix this.

**Comment by claboran** [comment]
@bwanshoom - I provided a fix for MyDomain. Plz take a look. Will test the new version with our project. Thanks in advance.

**Comment by bwanshoom** [comment]
Hi @claboran. Yep, thanks, I got the fix notification yesterday and pulled it - it works fine. Appreciate the quick fix.
